=== mpogue2/SquareDesk/SquareDesk-DEV/Taminations/info/tamination.dtd
<!--
    Copyright 2015 Brad Christie

    This file is part of Taminations.

    Taminations is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published
    by the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    Taminations is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with Taminations.  If not, see <http://www.gnu.org/licenses/>.
-->

<!ENTITY deg    "&#176;" ><!--=degree sign-->
<!ENTITY frac12 "&#189;" ><!--=fraction one-half-->
<!ENTITY frac14 "&#188;" ><!--=fraction one-quarter-->
<!ENTITY frac34 "&#190;" ><!--=fraction three-quarters-->
<!ENTITY mdash  "&#x2014;" ><!--=em dash-->
<!ENTITY ndash  "&#x2013;" ><!--=en dash-->
<!ENTITY middot "&#183;" ><!--/centerdot B: =middle dot-->
<!ENTITY bull   "&#x2022;" ><!--/bullet B: =round bullet, filled-->

<!--  Below are all the elements and attributes for animation xml files  -->
<!ELEMENT tamination (tam | tamxref)*>
<!ATTLIST tamination title CDATA #REQUIRED >

<!ELEMENT tam (formation?,path*,taminator?)>
<!ATTLIST tam title CDATA #REQUIRED
              group CDATA #IMPLIED
              from CDATA #IMPLIED
              formation CDATA #IMPLIED
              parts CDATA #IMPLIED
              fractions CDATA #IMPLIED
              difficulty CDATA #IMPLIED
              gender-specific CDATA #IMPLIED
              display CDATA #IMPLIED >

<!ELEMENT tamxref EMPTY>
<!ATTLIST tamxref title CDATA #REQUIRED
                  from CDATA #IMPLIED
                  group CDATA #IMPLIED
                  xref-link CDATA #REQUIRED
                  xref-title CDATA #IMPLIED
                  xref-from CDATA #IMPLIED >

<!ELEMENT taminator ANY>

<!ELEMENT path (move | movement)* >
<!ATTLIST path name CDATA #IMPLIED
               numbers CDATA #IMPLIED
               couples CDATA #IMPLIED >

<!--  Moves, movements, dancers, and formations are used in both animation files
      and the definition files moves.xml and formations.xml  -->
<!ELEMENT move EMPTY>
<!ATTLIST move select CDATA #REQUIRED
               beats CDATA #IMPLIED
               hands CDATA #IMPLIED
               reflect CDATA #IMPLIED
               scaleX CDATA #IMPLIED
               scaleY CDATA #IMPLIED
               offsetX CDATA #IMPLIED
               offsetY CDATA #IMPLIED >

<!ELEMENT movement EMPTY>
<!ATTLIST movement hands CDATA #REQUIRED
                   beats CDATA #REQUIRED
                   style CDATA #IMPLIED
                   cx1 CDATA #REQUIRED
                   cy1 CDATA #REQUIRED
                   cx2 CDATA #REQUIRED
                   cy2 CDATA #REQUIRED
                   x2 CDATA #REQUIRED
                   y2 CDATA #REQUIRED
                   cx3 CDATA #IMPLIED
                   cx4 CDATA #IMPLIED
                   cy4 CDATA #IMPLIED
                   x4 CDATA #IMPLIED
                   y4 CDATA #IMPLIED >

<!ELEMENT moves (path+)>

<!ELEMENT formations (formation+)>

<!ELEMENT formation (dancer+)>
<!ATTLIST formation name CDATA #IMPLIED >

<!ELEMENT dancer EMPTY >
<!ATTLIST dancer gender CDATA #REQUIRED
                 x CDATA #REQUIRED
                 y CDATA #REQUIRED
                 angle CDATA #REQUIRED >

=== mpogue2/SquareDesk/SquareDesk-DEV/Taminations/c3a/split_phantom_columns_lines_waves_concept.xml
<?xml version="1.0"?>
<!DOCTYPE tamination SYSTEM "tamination.dtd">
<!--

    Copyright 2017 Brad Christie

    This file is part of Taminations.

    Taminations is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published
    by the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    Taminations is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with Taminations.  If not, see <http://www.gnu.org/licenses/>.

-->
<tamination title="Split Phantom Columns-Lines-Waves Concept">

  <tam title="Split Phantom Columns Triple Cross" group="Split Phantom Columns">
    <formation>
      <dancer gender="boy" x="3" y="1" angle="180"/>
      <dancer gender="girl" x="1" y="1" angle="180"/>
      <dancer gender="girl" x="3" y="-1" angle="0"/>
      <dancer gender="boy" x="1" y="-1" angle="0"/>
      <dancer gender="phantom" x="3" y="3" angle="0"/>
      <dancer gender="phantom" x="-3" y="3" angle="0"/>
      <dancer gender="phantom" x="1" y="3" angle="0"/>
      <dancer gender="phantom" x="-1" y="3" angle="0"/>
    </formation>
    <path>
      <move select="Extend Right" beats="2" scaleX="2" scaleY="2"/>
    </path>
    <path>
      <move select="Extend Right" beats="2" scaleX="2" scaleY="2"/>
    </path>
    <path>
    </path>
    <path>
      <move select="Extend Right" beats="2" scaleX="2" scaleY="2"/>
    </path>
    <path>
    </path>
    <path>
      <move select="Extend Right" beats="2" scaleX="2" scaleY="2"/>
    </path>
    <path>
      <move select="Extend Right" beats="2" scaleX="2" scaleY="2"/>
    </path>
    <path>
      <move select="Extend Right" beats="2" scaleX="2" scaleY="2"/>
    </path>
  </tam>

  <tam title="Split Phantom Columns Something New" group="Split Phantom Columns">
    <formation>
      <dancer gender="boy" x="3" y="1" angle="180"/>
      <dancer gender="girl" x="1" y="1" angle="180"/>
      <dancer gender="girl" x="3" y="-1" angle="0"/>
      <dancer gender="boy" x="1" y="-1" angle="0"/>
      <dancer gender="phantom" x="3" y="3" angle="0"/>
      <dancer gender="phantom" x="-3" y="3" angle="0"/>
      <dancer gender="phantom" x="1" y="3" angle="0"/>
      <dancer gender="phantom" x="-1" y="3" angle="0"/>
    </formation>
    <path>
      <move select="Extend Left" beats="3" scaleX="3" scaleY=".5"/>
    </path>
    <path>
      <move select="U-Turn Right" beats="3" offsetX="1" offsetY="-.5"/>
    </path>
    <path>
      <move select="Run Right" scaleX=".5" scaleY=".75"/>
    </path>
    <path>
      <move select="U-Turn Right" beats="3" offsetX="2" offsetY="-.5"/>
    </path>
    <path>
      <move select="Run Right" scaleX=".5" scaleY=".75"/>
    </path>
    <path>
      <move select="Extend Left" beats="3" scaleX="3" scaleY=".5"/>
    </path>
    <path>
      <move select="U-Turn Right" beats="3" offsetX="2" offsetY="-.5"/>
    </path>
    <path>
      <move select="U-Turn Right" beats="3" offsetX="1" offsetY="-.5"/>
    </path>
  </tam>


  <tam title="Split Phantom Lines Acey Deucey" group="Split Phantom Lines">
    <formation>
      <dancer gender="boy" x="3" y="1" angle="180"/>
      <dancer gender="girl" x="1" y="1" angle="180"/>
      <dancer gender="girl" x="1" y="-3" angle="0"/>
      <dancer gender="boy" x="1" y="-1" angle="0"/>
      <dancer gender="phantom" x="3" y="3" angle="180"/>
      <dancer gender="phantom" x="-3" y="3" angle="180"/>
      <dancer gender="phantom" x="1" y="3" angle="180"/>
      <dancer gender="phantom" x="-3" y="1" angle="180"/>
    </formation>
    <path>
      <move select="Swing Left" scaleX=".5"/>
    </path>
    <path>
      <move select="Swing Left" scaleX=".5"/>
    </path>
    <path>
      <move select="Forward 2" beats="3"/>
    </path>
    <path>
      <move select="Swing Left" scaleX=".5"/>
    </path>
    <path>
      <move select="Forward 2" beats="3"/>
    </path>
    <path>
      <move select="Run Left" scaleX="2" scaleY="3"/>
    </path>
    <path>
      <move select="Run Left" scaleX="2" scaleY="3"/>
    </path>
    <path>
      <move select="Swing Left" scaleX=".5"/>
    </path>
  </tam>

  <tam title="Split Phantom Lines Load the Boat" group="Split Phantom Lines">
    <formation>
      <dancer gender="boy" x="1" y="3" angle="0"/>
      <dancer gender="girl" x="1" y="1" angle="0"/>
      <dancer gender="boy" x="1" y="-1" angle="0"/>
      <dancer gender="girl" x="1" y="-3" angle="0"/>
      <dancer gender="phantom" x="3" y="3" angle="180"/>
      <dancer gender="phantom" x="3" y="1" angle="180"/>
      <dancer gender="phantom" x="3" y="-1" angle="180"/>
      <dancer gender="phantom" x="3" y="-3" angle="180"/>
    </formation>
    <path>
      <move select="Forward 2"/>
      <move select="Lead Right" beats="3" scaleX="2" scaleY="3"/>
      <move select="Lead Right" beats="3" scaleX="3" scaleY="2"/>
      <move select="Quarter Right" beats="2" offsetX="2"/>
    </path>
    <path>
      <move select="Forward 2"/>
      <move select="Quarter Left"/>
      <move select="Flip Left"/>
      <move select="Extend Left" scaleY=".5"/>
      <move select="Extend Right" scaleY=".5"/>
    </path>
    <path>
      <move select="Forward 2"/>
      <move select="Quarter Right"/>
      <move select="Flip Right"/>
      <move select="Extend Left" scaleY=".5"/>
      <move select="Extend Right" scaleY=".5"/>
    </path>
    <path>
      <move select="Forward 2"/>
      <move select="Lead Left" beats="3" scaleY="3"/>
      <move select="Lead Left" beats="3" scaleX="3" />
      <move select="Quarter Left" beats="2" offsetX="2"/>
    </path>
    <path>
      <move select="Forward 2"/>
      <move select="Lead Left" beats="3" scaleY="3"/>
      <move select="Lead Left" beats="3" scaleX="3" />
      <move select="Quarter Left" beats="2" offsetX="2"/>
    </path>
    <path>
      <move select="Forward 2"/>
      <move select="Quarter Right"/>
      <move select="Flip Right"/>
      <move select="Forward 2"/>
    </path>
    <path>
      <move select="Forward 2"/>
      <move select="Quarter Left"/>
      <move select="Flip Left"/>
      <move select="Forward 2"/>
    </path>
    <path>
      <move select="Forward 2"/>
      <move select="Lead Right" beats="3" scaleY="3"/>
      <move select="Lead Right" beats="3" scaleX="3" />
      <move select="Quarter Right" beats="2" offsetX="2"/>
    </path>
  </tam>


  <tam title="Split Phantom Waves In Roll Circulate" group="Split Phantom Waves">
    <formation>
      <dancer gender="boy" x="1" y="3" angle="0"/>
      <dancer gender="girl" x="1" y="1" angle="180"/>
      <dancer gender="boy" x="1" y="-1" angle="0"/>
      <dancer gender="girl" x="1" y="-3" angle="180"/>
      <dancer gender="phantom" x="3" y="3" angle="0"/>
      <dancer gender="phantom" x="3" y="1" angle="180"/>
      <dancer gender="phantom" x="3" y="-1" angle="0"/>
      <dancer gender="phantom" x="3" y="-3" angle="180"/>
    </formation>
    <path>
      <move select="Forward 2" beats="3"/>
    </path>
    <path>
      <move select="Flip Right"/>
    </path>
    <path>
      <move select="Flip Left"/>
    </path>
    <path>
      <move select="Flip Right"/>
    </path>
    <path>
      <move select="Flip Right"/>
    </path>
    <path>
      <move select="Flip Left"/>
    </path>
    <path>
      <move select="Flip Right"/>
    </path>
    <path>
      <move select="Forward 2" beats="3"/>
    </path>
  </tam>

  <tam title="Split Phantom Waves Split Counter Rotate" group="Split Phantom Waves">
    <formation>
      <dancer gender="boy" x="1" y="3" angle="0"/>
      <dancer gender="girl" x="1" y="1" angle="180"/>
      <dancer gender="boy" x="1" y="-1" angle="0"/>
      <dancer gender="girl" x="1" y="-3" angle="180"/>
      <dancer gender="phantom" x="3" y="3" angle="0"/>
      <dancer gender="phantom" x="3" y="1" angle="180"/>
      <dancer gender="phantom" x="3" y="-1" angle="0"/>
      <dancer gender="phantom" x="3" y="-3" angle="180"/>
    </formation>
    <path>
      <move select="Counter Rotate Right 2 0" hands="right"/>
    </path>
    <path>
      <move select="Counter Rotate Right 0 -2" hands="right"/>
    </path>
    <path>
      <move select="Counter Rotate Right 2 0" hands="right"/>
    </path>
    <path>
      <move select="Counter Rotate Right 0 -2" hands="right"/>
    </path>
    <path>
      <move select="Counter Rotate Right 0 -2" hands="right"/>
    </path>
    <path>
      <move select="Counter Rotate Right 2 0" hands="right"/>
    </path>
    <path>
      <move select="Counter Rotate Right 0 -2" hands="right"/>
    </path>
    <path>
      <move select="Counter Rotate Right 2 0" hands="right"/>
    </path>
  </tam>

</tamination>

=== mpogue2/SquareDesk/SquareDesk-DEV/Taminations/plus/linear_cycle.xml
<?xml version="1.0"?>
<!DOCTYPE tamination SYSTEM "tamination.dtd">
<!--

    Copyright 2017 Brad Christie

    This file is part of Taminations.

    Taminations is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published
    by the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    Taminations is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with Taminations.  If not, see <http://www.gnu.org/licenses/>.

-->
<tamination title="Linear Cycle">

  <tam title="Linear Cycle"
       from="Right-Hand Wave"
       formation="Wave RH"
       parts="1.5;4" difficulty="1">
    <path>
      <move select="Hinge Right" />
      <move select="Forward 4" />
      <move select="Run Right" />
    </path>
    <path>
      <move select="Hinge Right" />
      <move select="Run Right" />
      <move select="Forward 2" />
      <move select="U-Turn Right" offsetX="2" />
    </path>
    <taminator>
      After the Hinge, be sure to let go of hands.  Do not hold
      hands again until the end of the call.
    </taminator>
  </tam>

  <tam title="Linear Cycle"
       from="Left-Hand Wave"
       formation="Wave LH"
       parts="1.5;4" difficulty="2">
    <path>
      <move select="Hinge Left" />
      <move select="Forward 4" />
      <move select="Run Left" />
    </path>
    <path>
      <move select="Hinge Left" />
      <move select="Run Left" />
      <move select="Forward 2" />
      <move select="U-Turn Left" offsetX="2" />
    </path>
  </tam>

  <tam title="Linear Cycle"
       from="Right-Hand Waves"
       formation="Ocean Waves RH BGGB"
       parts="1.5;4" difficulty="1">
    <path>
      <move select="Hinge Right" />
      <move select="Forward 4" />
      <move select="Run Right" />
    </path>
    <path>
      <move select="Hinge Right" />
      <move select="Run Right" />
      <move select="Forward 2" />
      <move select="U-Turn Right" offsetX="2" />
    </path>
    <path>
      <move select="Hinge Right" />
      <move select="Run Right" />
      <move select="Forward 2" />
      <move select="U-Turn Right" offsetX="2" />
    </path>
    <path>
      <move select="Hinge Right" />
      <move select="Forward 4" />
      <move select="Run Right" />
    </path>
    <taminator>
    Linear Cycle is NOT Recycle and Sweep a Quarter,
    </taminator>
  </tam>

  <tam title="Linear Cycle"
       from="Left-Hand Waves"
       formation="Ocean Waves LH BGGB"
       parts="1.5;4" difficulty="2">
    <path>
      <move select="Hinge Left" />
      <move select="Forward 4" />
      <move select="Run Left" />
    </path>
    <path>
      <move select="Hinge Left" />
      <move select="Run Left" />
      <move select="Forward 2" />
      <move select="U-Turn Left" offsetX="2" />
    </path>
    <path>
      <move select="Hinge Left" />
      <move select="Run Left" />
      <move select="Forward 2" />
      <move select="U-Turn Left" offsetX="2" />
    </path>
    <path>
      <move select="Hinge Left" />
      <move select="Forward 4" />
      <move select="Run Left" />
    </path>
  </tam>

  <tam title="Linear Cycle"
       from="Right-Hand Tidal Wave"
       formation="Tidal Wave RH BGGB"
       parts="1.5;3" difficulty="1">
    <path>
      <move select="Hinge Right" scaleY=".5" />
      <move select="Forward 2" />
      <move select="Flip Right" />
    </path>
    <path>
      <move select="Hinge Right" scaleY=".5" />
      <move select="Flip Right" />
      <move select="Forward" />
      <move select="U-Turn Right" beats="1" offsetX="1" />
    </path>
    <path>
      <move select="Hinge Right" scaleY=".5" />
      <move select="Flip Right" />
      <move select="Forward" />
      <move select="U-Turn Right" beats="1" offsetX="1" />
    </path>
    <path>
      <move select="Hinge Right" scaleY=".5" />
      <move select="Forward 2" />
      <move select="Flip Right" />
    </path>
  </tam>

  <tam title="Linear Cycle"
       from="Left-Hand Tidal Wave"
       formation="Tidal Wave LH BGGB"
       parts="1.5;3" difficulty="2">
    <path>
      <move select="Hinge Left" scaleY=".5" />
      <move select="Forward 2" />
      <move select="Flip Left" />
    </path>
    <path>
      <move select="Hinge Left" scaleY=".5" />
      <move select="Flip Left" />
      <move select="Forward" />
      <move select="U-Turn Left" beats="1" offsetX="1" />
    </path>
    <path>
      <move select="Hinge Left" scaleY=".5" />
      <move select="Flip Left" />
      <move select="Forward" />
      <move select="U-Turn Left" beats="1" offsetX="1" />
    </path>
    <path>
      <move select="Hinge Left" scaleY=".5" />
      <move select="Forward 2" />
      <move select="Flip Left" />
    </path>
  </tam>
</tamination>

=== mpogue2/SquareDesk/SquareDesk-DEV/Taminations/a1/transfer_the_column.xml
<?xml version="1.0"?>
<!DOCTYPE tamination SYSTEM "tamination.dtd">
<!--

    Copyright 2017 Brad Christie

    This file is part of Taminations.

    Taminations is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published
    by the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    Taminations is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with Taminations.  If not, see <http://www.gnu.org/licenses/>.

-->
<tamination title="Transfer the Column">

  <tam title="Transfer the Column"
       from="Right-Hand Columns">
     <formation>
      <dancer gender="girl" x="-1" y="3" angle="90"/>
      <dancer gender="girl" x="-1" y="-1" angle="90"/>
      <dancer gender="boy" x="-1" y="1" angle="90"/>
      <dancer gender="boy" x="-1" y="-3" angle="90"/>
    </formation>
    <path numbers="1 5" couples="3 1">
      <move select="Run Right" beats="3" scaleY="2" />
      <move select="Forward 4" />
      <move select="Lead Right" beats="2" scaleX="2" />
    </path>
    <path numbers="3 7" couples="2 4">
      <move select="Forward 2" />
      <move select="Swing Right" scaleX=".5" />
      <move select="Hinge Right" scaleX=".5" />
      <move select="Extend Right" beats="2" scaleX="2" scaleY=".5" />
    </path>
    <path numbers="2 6" couples="3 1">
      <move select="Forward 2" />
      <move select="Run Right" beats="3" scaleY="2" />
      <move select="Lead Right" beats="2" scaleX="2" />
    </path>
    <path numbers="4 8" couples="2 4">
      <move select="Forward 2" />
      <move select="Swing Right" scaleX=".5" />
      <move select="Hinge Right" scaleX=".5" />
      <move select="Extend Left" beats="2" scaleX="2" scaleY="1.5" />
    </path>
  </tam>

  <tam title="Transfer the Column"
       from="Left-Hand Columns">
     <formation>
      <dancer gender="boy" x="-1" y="-3" angle="270"/>
      <dancer gender="boy" x="-1" y="1" angle="270"/>
      <dancer gender="girl" x="-1" y="-1" angle="270"/>
      <dancer gender="girl" x="-1" y="3" angle="270"/>
    </formation>
    <path numbers="1 5" couples="2 4">
      <move select="Run Left" beats="3" scaleY="2" />
      <move select="Forward 4" />
      <move select="Lead Left" beats="2" scaleX="2" />
    </path>
    <path numbers="3 7" couples="3 1">
      <move select="Forward 2" />
      <move select="Swing Left" scaleX=".5" />
      <move select="Hinge Left" scaleX=".5" />
      <move select="Extend Left" beats="2" scaleX="2" scaleY=".5" />
    </path>
    <path numbers="2 6" couples="2 4">
      <move select="Forward 2" />
      <move select="Run Left" beats="3" scaleY="2" />
      <move select="Lead Left" beats="2" scaleX="2" />
    </path>
    <path numbers="4 8" couples="3 1">
      <move select="Forward 2" />
      <move select="Swing Left" scaleX=".5" />
      <move select="Hinge Left" scaleX=".5" />
      <move select="Extend Right" beats="2" scaleX="2" scaleY="1.5" />
    </path>
  </tam>
</tamination>

=== mpogue2/SquareDesk/SquareDesk-DEV/Taminations/c2/3_by_1_transfer_the_column.xml
<?xml version="1.0"?>
<!DOCTYPE tamination SYSTEM "tamination.dtd">
<!--

    Copyright 2017 Brad Christie

    This file is part of Taminations.

    Taminations is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published
    by the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    Taminations is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with Taminations.  If not, see <http://www.gnu.org/licenses/>.

-->
<tamination title="3 by 1 Transfer The Column">

  <tam title="3 by 1 Transfer the Column"
       from="Right-Hand Columns">
    <formation>
      <dancer gender="girl" y="3" x="-1" angle="90"/>
      <dancer gender="boy" y="1" x="-1" angle="90"/>
      <dancer gender="girl" y="-1" x="-1" angle="90"/>
      <dancer gender="boy" y="-3" x="-1" angle="90"/>
    </formation>
    <path couples="4 2">
      <move select="Run Right" beats="3" scaleY="2" />
      <move select="Forward 4" />
      <move select="Lead Right" beats="2.5" scaleX="2" />
    </path>
    <path couples="4 2">
      <move select="Forward 2" />
      <move select="Run Right" beats="3" scaleY="2" />
      <move select="Lead Right" beats="4.5" scaleX="4" />
    </path>
    <path couples="3 1">
      <move select="Forward 2" />
      <move select="Forward 2" />
      <move select="Run Right" beats="4" scaleY="2" offsetX="1" />
      <move select="Lead Right" />
    </path>
    <path couples="3 1">
      <move select="Forward 2" />
      <move select="Forward" />
      <move select="Cast Right" />
      <move select="Forward 2" />
    </path>
  </tam>

  <tam title="3 by 1 Transfer the Column"
       from="Left-Hand Columns">
     <formation>
      <dancer gender="girl" x="3" y="-1" angle="0"/>
      <dancer gender="boy" x="-1" y="-1" angle="0"/>
      <dancer gender="girl" x="1" y="-1" angle="0"/>
      <dancer gender="boy" x="-3" y="-1" angle="0"/>
    </formation>
    <path>
      <move select="Run Left" beats="3" scaleY="2" />
      <move select="Forward 4" />
      <move select="Lead Left" beats="2.5" scaleX="2" />
    </path>
    <path>
      <move select="Forward 2" />
      <move select="Forward 2" />
      <move select="Run Left" beats="4" scaleY="2" offsetX="1" />
      <move select="Lead Left" />
    </path>
    <path>
      <move select="Forward 2" />
      <move select="Run Left" beats="3" scaleY="2" />
      <move select="Lead Left" beats="4.5" scaleX="4" />
    </path>
    <path>
      <move select="Forward 2" />
      <move select="Forward" />
      <move select="Cast Left" />
      <move select="Forward 2" />
    </path>
  </tam>
</tamination>

=== mpogue2/SquareDesk/SquareDesk-DEV/Taminations/b1/courtesy_turn.xml
<?xml version="1.0"?>
<!DOCTYPE tamination SYSTEM "tamination.dtd">
<!--

    Copyright 2017 Brad Christie

    This file is part of Taminations.

    Taminations is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published
    by the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    Taminations is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with Taminations.  If not, see <http://www.gnu.org/licenses/>.

-->
<tamination title="Courtesy Turn">

  <tam title="Courtesy Turn"
       from="Couples Facing Out"
       formation="Couples Facing Out">
    <path>
      <move select="Belle Wheel" scaleX="0.67" />
    </path>
    <path>
      <move select="Beau Wheel" scaleX="0.67" />
    </path>
  </tam>

  <tam title="Courtesy Turn"
       from="Lines Facing Out"
       formation="Lines Facing Out">
    <path>
      <move select="Belle Wheel" scaleX="0.67" />
    </path>
    <path>
      <move select="Beau Wheel" scaleX="0.67" />
    </path>
    <path>
      <move select="Belle Wheel" scaleX="0.67" />
    </path>
    <path>
      <move select="Beau Wheel" scaleX="0.67" />
    </path>
  </tam>

  <tam title="Heads Pass Thru and Courtesy Turn" group=" "
       formation="Static Square" fractions="6">
    <path>
      <move select="Extend Left" beats="3" scaleX="3" scaleY=".5"/>
      <move select="Extend Right" beats="3" scaleX="3" scaleY=".5"/>
      <move select="Beau Wheel" scaleX="0.67" />
    </path>
    <path>
      <move select="Extend Left" beats="3" scaleX="3" scaleY=".5"/>
      <move select="Extend Right" beats="3" scaleX="3" scaleY=".5"/>
      <move select="Belle Wheel" scaleX="0.67" />
    </path>
    <path>
    </path>
    <path>
    </path>
  </tam>

  <tam title="All 4 Ladies make a right-hand star, turn it once around; boys Courtesy Turn your girl"
       group=" " formation="Static Square">
    <path>
      <move select="Stand" beats="6"/>
      <move select="Quarter Left" beats="3" offsetY="-2"/>
      <move select="Quarter Left" beats="2"/>
      <move select="Beau Wheel" scaleX="0.67" />
    </path>
    <path>
      <move select="Extend Left" beats="4" scaleX="3" scaleY="2"/>
      <move select="Swing Right"/>
      <move select="Extend Right" beats="4" scaleX="3" scaleY="2"/>
      <move select="Belle Wheel" scaleX="0.67" />
    </path>
    <path>
      <move select="Stand" beats="6"/>
      <move select="Quarter Left" beats="3" offsetY="-2"/>
      <move select="Quarter Left" beats="2"/>
      <move select="Beau Wheel" scaleX="0.67" />
    </path>
    <path>
      <move select="Extend Left" beats="4" scaleX="3" scaleY="2"/>
      <move select="Swing Right"/>
      <move select="Extend Right" beats="4" scaleX="3" scaleY="2"/>
      <move select="Belle Wheel" scaleX="0.67" />
    </path>
    <taminator>
      This is also called 4 Ladies Chain All 4 Quarters
    </taminator>
  </tam>

</tamination>
