=== mpogue2/SquareDesk/SquareDesk-DEV/Taminations/info/tamination.dtd
<!--
    Copyright 2015 Brad Christie

    This file is part of Taminations.

    Taminations is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published
    by the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    Taminations is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with Taminations.  If not, see <http://www.gnu.org/licenses/>.
-->

<!ENTITY deg    "&#176;" ><!--=degree sign-->
<!ENTITY frac12 "&#189;" ><!--=fraction one-half-->
<!ENTITY frac14 "&#188;" ><!--=fraction one-quarter-->
<!ENTITY frac34 "&#190;" ><!--=fraction three-quarters-->
<!ENTITY mdash  "&#x2014;" ><!--=em dash-->
<!ENTITY ndash  "&#x2013;" ><!--=en dash-->
<!ENTITY middot "&#183;" ><!--/centerdot B: =middle dot-->
<!ENTITY bull   "&#x2022;" ><!--/bullet B: =round bullet, filled-->

<!--  Below are all the elements and attributes for animation xml files  -->
<!ELEMENT tamination (tam | tamxref)*>
<!ATTLIST tamination title CDATA #REQUIRED >

<!ELEMENT tam (formation?,path*,taminator?)>
<!ATTLIST tam title CDATA #REQUIRED
              group CDATA #IMPLIED
              from CDATA #IMPLIED
              formation CDATA #IMPLIED
              parts CDATA #IMPLIED
              fractions CDATA #IMPLIED
              difficulty CDATA #IMPLIED
              gender-specific CDATA #IMPLIED
              display CDATA #IMPLIED >

<!ELEMENT tamxref EMPTY>
<!ATTLIST tamxref title CDATA #REQUIRED
                  from CDATA #IMPLIED
                  group CDATA #IMPLIED
                  xref-link CDATA #REQUIRED
                  xref-title CDATA #IMPLIED
                  xref-from CDATA #IMPLIED >

<!ELEMENT taminator ANY>

<!ELEMENT path (move | movement)* >
<!ATTLIST path name CDATA #IMPLIED
               numbers CDATA #IMPLIED
               couples CDATA #IMPLIED >

<!--  Moves, movements, dancers, and formations are used in both animation files
      and the definition files moves.xml and formations.xml  -->
<!ELEMENT move EMPTY>
<!ATTLIST move select CDATA #REQUIRED
               beats CDATA #IMPLIED
               hands CDATA #IMPLIED
               reflect CDATA #IMPLIED
               scaleX CDATA #IMPLIED
               scaleY CDATA #IMPLIED
               offsetX CDATA #IMPLIED
               offsetY CDATA #IMPLIED >

<!ELEMENT movement EMPTY>
<!ATTLIST movement hands CDATA #REQUIRED
                   beats CDATA #REQUIRED
                   style CDATA #IMPLIED
                   cx1 CDATA #REQUIRED
                   cy1 CDATA #REQUIRED
                   cx2 CDATA #REQUIRED
                   cy2 CDATA #REQUIRED
                   x2 CDATA #REQUIRED
                   y2 CDATA #REQUIRED
                   cx3 CDATA #IMPLIED
                   cx4 CDATA #IMPLIED
                   cy4 CDATA #IMPLIED
                   x4 CDATA #IMPLIED
                   y4 CDATA #IMPLIED >

<!ELEMENT moves (path+)>

<!ELEMENT formations (formation+)>

<!ELEMENT formation (dancer+)>
<!ATTLIST formation name CDATA #IMPLIED >

<!ELEMENT dancer EMPTY >
<!ATTLIST dancer gender CDATA #REQUIRED
                 x CDATA #REQUIRED
                 y CDATA #REQUIRED
                 angle CDATA #REQUIRED >

=== mpogue2/SquareDesk/SquareDesk-DEV/Taminations/a1/left.xml
<?xml version="1.0"?>
<!DOCTYPE tamination SYSTEM "tamination.dtd">
<!--

    Copyright 2017 Brad Christie

    This file is part of Taminations.

    Taminations is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published
    by the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    Taminations is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with Taminations.  If not, see <http://www.gnu.org/licenses/>.

-->
<tamination title="Left">


  <tam title="Left Dosado" group="Left"
       formation="Facing Couples">
    <path>
      <move select="Extend Right" scaleX="2" scaleY=".5" />
      <move select="Extend Left" scaleY=".5" />
      <move select="Retreat Left" scaleY=".5" />
      <move select="Retreat Right" scaleX="2" scaleY=".5" />
    </path>
    <path>
      <move select="Extend Right" scaleX="2" scaleY=".5" />
      <move select="Extend Left" scaleY=".5" />
      <move select="Retreat Left" scaleY=".5" />
      <move select="Retreat Right" scaleX="2" scaleY=".5" />
    </path>
  </tam>

  <tamxref title="Left Swing Thru" group="Left"
           xref-link="b2/swing_thru"
           xref-title="Left Swing Thru"
           xref-from="Right-Hand Wave"/>

  <tam title="Left 3/4 Tag the Line" formation="Two-Faced Lines LH" group="Left">
    <path>
      <move select="Lead Left"/>
      <move select="Forward 2" beats="3"/>
    </path>
    <path>
      <move select="Lead Left"/>
      <move select="Extend Left" beats="3" scaleX="3" scaleY="2"/>
    </path>
    <path>
      <move select="Lead Left"/>
      <move select="Forward 3"/>
    </path>
    <path>
      <move select="Lead Left"/>
      <move select="Forward 2" beats="3"/>
    </path>
  </tam>

  <tamxref title="Left Touch a Quarter" group="Left"
           xref-link="b2/touch_a_quarter"
           xref-title="Left Touch a Quarter"
           xref-from="Facing Couples"/>

  <tamxref title="Left Track Two" group="Left"
           xref-link="plus/track_ii"
           xref-title="Left Track Two"/>

  <tam title="Left Turn Thru" group="Left"
       from="Facing Couples"
       formation="Facing Couples">
    <path>
      <move select="Extend Right" scaleX="2" scaleY=".5" />
      <move select="Swing Left" hands="gripright" beats="2" scaleX=".5" scaleY=".5" />
      <move select="Extend Left" scaleX="2" scaleY=".5" />
    </path>
    <path>
      <move select="Extend Right" scaleX="2" scaleY=".5" />
      <move select="Swing Left" hands="gripright" beats="2" scaleX=".5" scaleY=".5" />
      <move select="Extend Left" scaleX="2" scaleY=".5" />
    </path>
  </tam>

  <tam title="Left Wheel and Deal" formation="Lines Facing Out" group="Left">
    <path>
      <move select="Run Left" beats="4" hands="left" scaleX="2" scaleY="2" offsetX="1" />
    </path>
    <path>
      <move select="U-Turn Left" beats="4" hands="right" offsetX="1" />
    </path>
    <path>
      <move select="U-Turn Right" beats="4" hands="left" offsetX="-1" />
    </path>
    <path>
      <move select="Run Right" beats="4" hands="right" scaleY="2" offsetX="-1" />
    </path>
  </tam>

  <tamxref title="Left (A-1) Partner Hinge" group="Left (A-1)"
           xref-link="a1/partner_hinge"
           xref-title="Left Partner Hinge"
           xref-from="Lines Facing Out"/>

  <tamxref title="Left (A-1) Quarter Thru" group="Left (A-1)"
           xref-link="a1/quarter_thru"
           xref-title="Left Quarter Thru"
           xref-from="Left-Hand Box"/>

  <tamxref title="Left (A-1) Split Square Thru" group="Left (A-1)"
           xref-link="a1/split_square_thru"
           xref-title="Left Split Square Thru"/>

  <tamxref title="Left (A-1) Square Chain Thru" group="Left (A-1)"
           xref-link="a1/left_square_chain_thru"
           xref-title="Left Square Chain Thru"
           xref-from="Facing Couples"/>

  <tamxref title="Left (A-1) Turn and Deal" group="Left (A-1)"
           xref-link="a1/turn_and_deal"
           xref-title="Left Turn and Deal"/>

  <tamxref title="Left (A-2) Pass and Roll" group="Left (A-2)"
           xref-link="a2/pass_and_roll"
           xref-title="Left Pass and Roll"/>

  <tamxref title="Left (A-2) Remake" group="Left (A-2)"
           xref-link="a2/remake"
           xref-title="Left Remake"/>

  <tamxref title="Left (A-2) Spin the Windmill Right" group="Left (A-2)"
           xref-link="a2/spin_the_windmill"
           xref-title="Left Spin the Windmill Right"
           xref-from="Trade By"/>

</tamination>

=== mpogue2/SquareDesk/SquareDesk-DEV/Taminations/c1/scoot_and_plenty.xml
<?xml version="1.0"?>
<!DOCTYPE tamination SYSTEM "tamination.dtd">
<!--

    Copyright 2017 Brad Christie

    This file is part of Taminations.

    Taminations is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published
    by the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    Taminations is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with Taminations.  If not, see <http://www.gnu.org/licenses/>.

-->
<tamination title="Scoot and Plenty">



  <tam title="Scoot and Plenty"
       from="Quarter Tag"
       formation="Quarter Tag"
       parts="6;6;7" >
    <path>
      <move select="Extend Left" beats="1.5" scaleX="1.5" scaleY="1.5" />
      <move select="Swing Right" scaleX=".75" scaleY=".75" />
      <move select="Forward" beats="1.5" scaleX="1.5" />
      <move select="Flip Right" offsetX="-1" />
      <move select="Forward 4" beats="3" />
      <move select="Flip Right" />
      <move select="Forward 4" />
      <move select="Run Right" beats="6" offsetX="-2" />
    </path>
    <path>
      <move select="Forward" beats="1.5" scaleX="1.5" />
      <move select="Swing Right" scaleX=".75" scaleY=".75" />
      <move select="Extend Right" beats="1.5" scaleX="1.5" scaleY="1.5" />
      <move select="Flip Right" beats="5" scaleX="2" scaleY="2" />
      <move select="Forward" />
      <move select="Forward 4" />
      <move select="Run Right" />
      <move select="Forward 2" beats="6" />
    </path>
    <path>
      <move select="Extend Right" beats="1.5" scaleX="1.5" scaleY=".5" />
      <move select="Swing Right" scaleX=".75" scaleY=".75" />
      <move select="Forward" beats="1.5" scaleX="1.5" />
      <move select="Forward 2" beats="6" />
      <move select="Flip Right" />
      <move select="Forward 4" />
      <move select="Lead Right" beats="4" scaleX="2" scaleY="3" />
      <move select="Lead Right" beats="2" />
    </path>
    <path>
      <move select="Forward" beats="1.5" scaleX="1.5" />
      <move select="Swing Right" scaleX=".75" scaleY=".75" />
      <move select="Extend Left" beats="1.5" scaleX="1.5" scaleY=".5" />
      <move select="Flip Right" beats="6" offsetX="2" />
      <move select="Forward 4" />
      <move select="Flip Right" />
      <move select="Forward 4" beats="3.5" />
      <move select="Run Right" beats="2.5" offsetX="1" />
    </path>
  </tam>

  <tam title="Scoot and Plenty"
       from="Left-Hand Quarter Tag"
       formation="Quarter Tag LH"
       parts="6;6;7" >
    <path>
      <move select="Forward" beats="1.5" scaleX="1.5" />
      <move select="Swing Left" scaleX=".75" scaleY=".75" />
      <move select="Extend Left" beats="1.5" scaleX="1.5" scaleY="1.5" />
      <move select="Flip Left" beats="5" scaleX="2" scaleY="2" />
      <move select="Forward" />
      <move select="Forward 4" />
      <move select="Run Left" />
      <move select="Forward 2" beats="6" />
    </path>
    <path>
      <move select="Extend Right" beats="1.5" scaleX="1.5" scaleY="1.5" />
      <move select="Swing Left" scaleX=".75" scaleY=".75" />
      <move select="Forward" beats="1.5" scaleX="1.5" />
      <move select="Flip Left" offsetX="-1" />
      <move select="Forward 4" beats="3" />
      <move select="Flip Left" />
      <move select="Forward 4" />
      <move select="Run Left" beats="6" offsetX="-2" />
    </path>
    <path>
      <move select="Extend Left" beats="1.5" scaleX="1.5" scaleY=".5" />
      <move select="Swing Left" scaleX=".75" scaleY=".75" />
      <move select="Forward" beats="1.5" scaleX="1.5" />
      <move select="Forward 2" beats="6" />
      <move select="Flip Left" />
      <move select="Forward 4" />
      <move select="Lead Left" beats="4" scaleX="2" scaleY="3" />
      <move select="Lead Left" beats="2" />
    </path>
    <path>
      <move select="Forward" beats="1.5" scaleX="1.5" />
      <move select="Swing Left" scaleX=".75" scaleY=".75" />
      <move select="Extend Right" beats="1.5" scaleX="1.5" scaleY=".5" />
      <move select="Flip Left" beats="6" offsetX="2" />
      <move select="Forward 4" />
      <move select="Flip Left" />
      <move select="Forward 4" beats="3.5" />
      <move select="Run Left" beats="2.5" offsetX="1" />
    </path>
  </tam>

</tamination>

=== mpogue2/SquareDesk/SquareDesk-DEV/Taminations/c2/sock_it_to_me.xml
<?xml version="1.0"?>
<!DOCTYPE tamination SYSTEM "tamination.dtd">
<!--

    Copyright 2017 Brad Christie

    This file is part of Taminations.

    Taminations is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published
    by the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    Taminations is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with Taminations.  If not, see <http://www.gnu.org/licenses/>.

-->
<tamination title="Sock It To Me">
  
  

  <tam title="Sock It To Me"
       from="Lines Facing Out"
       formation="Lines Facing Out"
       fractions="" >
    <path>
      <move select="Flip Left" beats="6" />
    </path>
    <path>
      <move select="Flip Left" beats="6" />
    </path>
    <path>
      <move select="Flip Left" beats="6" />
    </path>
    <path>
      <move select="Run Right" beats="6" scaleX="2" scaleY="3" />
    </path>
  </tam>

  <tam title="Sock It To Me"
       from="Inverted Lines"
       formation="Inverted Lines Ends Facing Out"
       fractions="" >
    <path>
      <move select="Flip Left" beats="6" />
    </path>
    <path>
      <move select="Flip Right" beats="6" />
    </path>
    <path>
      <move select="Flip Right" beats="6" />
    </path>
    <path>
      <move select="Run Right" beats="6" scaleX="2" scaleY="3" />
    </path>
  </tam>
</tamination>

=== mpogue2/SquareDesk/SquareDesk-DEV/Taminations/c3a/1_4_wheel_the_ocean.xml
<?xml version="1.0"?>
<!DOCTYPE tamination SYSTEM "tamination.dtd">
<!--

    Copyright 2017 Brad Christie

    This file is part of Taminations.

    Taminations is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published
    by the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    Taminations is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with Taminations.  If not, see <http://www.gnu.org/licenses/>.

-->
<tamination title="1/4 Wheel the Ocean">

  <tam title="1/4 Wheel the Ocean" from="Left-Hand Two-Faced Line"
       formation="Two-Faced Line LH" parts="1.5">
    <path numbers="3 2" couples="3 1">
      <move select="BackHinge Right" />
      <move select="Stand" beats="4" hands="nohands" />
    </path>
    <path numbers="4 1" couples="3 1">
      <move select="Hinge Left" />
      <move select="Extend Left" hands="right" beats="3" scaleX="3" scaleY="2" />
      <move select="Forward" />
    </path>
  </tam>

  <tam title="1/4 Wheel the Ocean"
       from="Left-Hand Two-Faced Lines"
       formation="Two-Faced Lines LH"
       parts="1.5" >
    <path>
      <move select="Hinge Left" />
      <move select="Extend Left" hands="right" beats="3" scaleX="3" scaleY="2" />
      <move select="Forward" />
    </path>
    <path>
      <move select="BackHinge Right" />
      <move select="Stand" beats="4" hands="nohands" />
    </path>
    <path>
      <move select="BackHinge Right" />
      <move select="Stand" beats="4" hands="nohands" />
    </path>
    <path>
      <move select="Hinge Left" />
      <move select="Extend Left" hands="right" beats="3" scaleX="3" scaleY="2" />
      <move select="Forward" />
    </path>
  </tam>

  <tam title="1/4 Wheel the Ocean" from="Left-Hand Two-Faced Tidal Line"
       formation="Two-Faced Tidal Line LH" parts="1.5">
    <path>
      <move select="Hinge Left" scaleY=".5"/>
      <move select="Extend Left" hands="right" beats="2" scaleY="2" />
      <move select="Forward"/>
    </path>
    <path>
      <move select="BackHinge Right" scaleY=".5"/>
      <move select="Stand" beats="3" hands="nohands" />
    </path>
    <path>
      <move select="BackHinge Right" scaleY=".5"/>
      <move select="Stand" beats="3" hands="nohands" />
    </path>
    <path>
      <move select="Hinge Left" scaleY=".5" />
      <move select="Extend Left" hands="right" beats="2" scaleY="2" />
      <move select="Forward" />
    </path>
  </tam>

</tamination>

=== mpogue2/SquareDesk/SquareDesk-DEV/Taminations/c1/step_and_flip.xml
<?xml version="1.0"?>
<!DOCTYPE tamination SYSTEM "tamination.dtd">
<!--

    Copyright 2017 Brad Christie

    This file is part of Taminations.

    Taminations is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published
    by the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    Taminations is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with Taminations.  If not, see <http://www.gnu.org/licenses/>.

-->
<tamination title="Step and Flip">

  <tam title="Step and Flip"
       from="Lines Facing Out"
       formation="Lines Facing Out" >
    <path>
      <move select="Flip Left" offsetX="-1" />
    </path>
    <path>
      <move select="Forward" hands="left" />
    </path>
    <path>
      <move select="Forward" hands="right" />
    </path>
    <path>
      <move select="Flip Right" offsetX="-1" />
    </path>
  </tam>

  <tam title="Step and Flip"
       from="Inverted Lines Ends Facing In"
       formation="Inverted Lines Ends Facing In" >
    <path>
      <move select="Flip Right" offsetX="1" />
    </path>
    <path>
      <move select="Forward" hands="left" />
    </path>
    <path>
      <move select="Forward" hands="right" />
    </path>
    <path>
      <move select="Flip Left" offsetX="1" />
    </path>
  </tam>

  <tam title="Step and Flip"
       from="Inverted Lines Ends Facing Out"
       formation="Inverted Lines Ends Facing Out" >
    <path>
      <move select="Flip Left" offsetX="1" />
    </path>
    <path>
      <move select="Forward" hands="left" />
    </path>
    <path>
      <move select="Forward" hands="right" />
    </path>
    <path>
      <move select="Flip Right" offsetX="1" />
    </path>
  </tam>

  <tam title="Step and Flip" from="3 and 1 Lines">
    <formation>
      <dancer gender="boy" y="2" x="1" angle="90"/>
      <dancer gender="girl" y="2" x="3" angle="90"/>
      <dancer gender="boy" y="2" x="-3" angle="90"/>
      <dancer gender="girl" y="2" x="-1" angle="270"/>
    </formation>
    <path>
      <move select="Forward" beats="3" scaleX="1.5"/>
    </path>
    <path>
      <move select="Flip Left"/>
    </path>
    <path>
      <move select="Flip Right"/>
    </path>
    <path>
      <move select="Forward" beats="3" scaleX="1.5"/>
    </path>
  </tam>

  <tam title="Step and Flip"
       from="Tidal Lines">
    <formation name="Tidal Line RH">
      <dancer gender="boy" x="0" y="3.5" angle="0"/>
      <dancer gender="girl" x="0" y="2.5" angle="0"/>
      <dancer gender="boy" x="0" y=".5" angle="0"/>
      <dancer gender="girl" x="0" y="1.5" angle="0"/>
    </formation>
    <path>
      <move select="Flip Right"  offsetY="1.5" />
    </path>
    <path>
      <move select="Extend Left" hands="right" beats="3" scaleX="3" scaleY=".5" />
    </path>
    <path>
      <move select="Flip Left"  offsetY="-1.5" />
    </path>
    <path>
      <move select="Extend Right" hands="left" beats="3" scaleX="3" scaleY=".5" />
    </path>
  </tam>

  <tam title="Step and Flip and Roll" group=" "
       from="Lines Facing Out"
       formation="Lines Facing Out" >
    <path>
      <move select="Flip Left" offsetX="-1" />
      <move select="Quarter Left"/>
    </path>
    <path>
      <move select="Forward" hands="left" />
    </path>
    <path>
      <move select="Forward" hands="right" />
    </path>
    <path>
      <move select="Flip Right" offsetX="-1" />
      <move select="Quarter Right"/>
    </path>
  </tam>

  <tam title="As Couples Step and Flip" group=" ">
    <formation name="Tidal Line RH">
      <dancer gender="boy" x="0" y="3.5" angle="0"/>
      <dancer gender="girl" x="0" y="2.5" angle="0"/>
      <dancer gender="boy" x="0" y=".5" angle="0"/>
      <dancer gender="girl" x="0" y="1.5" angle="0"/>
    </formation>
    <path>
      <move select="Swing Right" scaleY="1.25"/>
    </path>
    <path>
      <move select="U-Turn Right" hands="left" offsetY=".5"/>
    </path>
    <path>
      <move select="Extend Left" beats="3" hands="left" scaleX="3" scaleY=".5"/>
    </path>
    <path>
      <move select="Extend Left" beats="3" hands="right" scaleX="3" scaleY="1.5"/>
    </path>
  </tam>

  <tam title="Stretch Step and Flip" group=" "
       formation="Inverted Lines Ends Facing In" >
    <path>
      <move select="Forward 2"/>
      <move select="Run Right" offsetX="1" />
    </path>
    <path>
      <move select="Forward" hands="left" />
    </path>
    <path>
      <move select="Forward" hands="right" />
    </path>
    <path>
      <move select="Extend Left" beats="2" scaleX="2"/>
      <move select="Flip Left" offsetX="1" scaleY=".5"/>
    </path>
  </tam>

  <tam title="Tandem Step and Flip" group=" "
       formation="Ocean Waves RH BGGB">
    <path>
      <move select="Forward 3"/>
      <move select='Run Right'/>
    </path>
    <path>
      <move select="Forward 3"/>
    </path>
    <path>
      <move select="Forward 5"/>
    </path>
    <path>
      <move select="Run Right"/>
      <move select="Forward 3"/>
    </path>
  </tam>

</tamination>
