=== mpogue2/SquareDesk/SquareDesk-DEV/Taminations/info/tamination.dtd
<!--
    Copyright 2015 Brad Christie

    This file is part of Taminations.

    Taminations is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published
    by the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    Taminations is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with Taminations.  If not, see <http://www.gnu.org/licenses/>.
-->

<!ENTITY deg    "&#176;" ><!--=degree sign-->
<!ENTITY frac12 "&#189;" ><!--=fraction one-half-->
<!ENTITY frac14 "&#188;" ><!--=fraction one-quarter-->
<!ENTITY frac34 "&#190;" ><!--=fraction three-quarters-->
<!ENTITY mdash  "&#x2014;" ><!--=em dash-->
<!ENTITY ndash  "&#x2013;" ><!--=en dash-->
<!ENTITY middot "&#183;" ><!--/centerdot B: =middle dot-->
<!ENTITY bull   "&#x2022;" ><!--/bullet B: =round bullet, filled-->

<!--  Below are all the elements and attributes for animation xml files  -->
<!ELEMENT tamination (tam | tamxref)*>
<!ATTLIST tamination title CDATA #REQUIRED >

<!ELEMENT tam (formation?,path*,taminator?)>
<!ATTLIST tam title CDATA #REQUIRED
              group CDATA #IMPLIED
              from CDATA #IMPLIED
              formation CDATA #IMPLIED
              parts CDATA #IMPLIED
              fractions CDATA #IMPLIED
              difficulty CDATA #IMPLIED
              gender-specific CDATA #IMPLIED
              display CDATA #IMPLIED >

<!ELEMENT tamxref EMPTY>
<!ATTLIST tamxref title CDATA #REQUIRED
                  from CDATA #IMPLIED
                  group CDATA #IMPLIED
                  xref-link CDATA #REQUIRED
                  xref-title CDATA #IMPLIED
                  xref-from CDATA #IMPLIED >

<!ELEMENT taminator ANY>

<!ELEMENT path (move | movement)* >
<!ATTLIST path name CDATA #IMPLIED
               numbers CDATA #IMPLIED
               couples CDATA #IMPLIED >

<!--  Moves, movements, dancers, and formations are used in both animation files
      and the definition files moves.xml and formations.xml  -->
<!ELEMENT move EMPTY>
<!ATTLIST move select CDATA #REQUIRED
               beats CDATA #IMPLIED
               hands CDATA #IMPLIED
               reflect CDATA #IMPLIED
               scaleX CDATA #IMPLIED
               scaleY CDATA #IMPLIED
               offsetX CDATA #IMPLIED
               offsetY CDATA #IMPLIED >

<!ELEMENT movement EMPTY>
<!ATTLIST movement hands CDATA #REQUIRED
                   beats CDATA #REQUIRED
                   style CDATA #IMPLIED
                   cx1 CDATA #REQUIRED
                   cy1 CDATA #REQUIRED
                   cx2 CDATA #REQUIRED
                   cy2 CDATA #REQUIRED
                   x2 CDATA #REQUIRED
                   y2 CDATA #REQUIRED
                   cx3 CDATA #IMPLIED
                   cx4 CDATA #IMPLIED
                   cy4 CDATA #IMPLIED
                   x4 CDATA #IMPLIED
                   y4 CDATA #IMPLIED >

<!ELEMENT moves (path+)>

<!ELEMENT formations (formation+)>

<!ELEMENT formation (dancer+)>
<!ATTLIST formation name CDATA #IMPLIED >

<!ELEMENT dancer EMPTY >
<!ATTLIST dancer gender CDATA #REQUIRED
                 x CDATA #REQUIRED
                 y CDATA #REQUIRED
                 angle CDATA #REQUIRED >

=== mpogue2/SquareDesk/SquareDesk-DEV/Taminations/c3b/sidetrack.xml
<?xml version="1.0"?>
<!DOCTYPE tamination SYSTEM "tamination.dtd">
<!--

    Copyright 2017 Brad Christie

    This file is part of Taminations.

    Taminations is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published
    by the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    Taminations is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with Taminations.  If not, see <http://www.gnu.org/licenses/>.

-->
<tamination title="Sidetrack">

  <tam title="Sidetrack" from="Right-Hand Columns" parts="1.5;4">
    <formation>
      <dancer gender="boy" x="3" y="1" angle="0"/>
      <dancer gender="girl" x="3" y="-1" angle="180"/>
      <dancer gender="girl" x="1" y="-1" angle="180"/>
      <dancer gender="boy" x="1" y="1" angle="0"/>
    </formation>
    <path>
      <move select="Quarter Right" offsetY="1"/>
      <move select="Counter Rotate Right 5 -1" beats="4"/>
      <move select="Quarter Right" offsetX="1"/>
    </path>
    <path>
      <move select="Quarter Left" offsetY="1"/>
      <move select="Counter Rotate Right 1 -5" beats="4"/>
      <move select="Quarter Right" offsetX="-1"/>
    </path>
    <path>
      <move select="Quarter Right" offsetY="1"/>
      <move select="Counter Rotate Left 3 -1" beats="4"/>
      <move select="Quarter Left" offsetX="1"/>
    </path>
    <path>
      <move select="Quarter Left" offsetY="1"/>
      <move select="Counter Rotate Left -1 3" beats="4"/>
      <move select="Quarter Left" offsetX="-1"/>
    </path>
  </tam>

  <tam title="Sidetrack" from="Right-Hand Two-Faced Lines"
       formation="Two-Faced Lines RH" parts="1.5;4">
    <path>
      <move select="Quarter Left" offsetX="1"/>
      <move select="Counter Rotate Right -2 -4" hands="right" beats="4"/>
      <move select="Quarter Right" offsetY="1"/>
    </path>
    <path>
      <move select="Quarter Left" offsetX="1"/>
      <move select="Counter Rotate Right 0 -2" hands="right" beats="4"/>
      <move select="Quarter Right" offsetY="1"/>
    </path>
    <path>
      <move select="Quarter Right" offsetX="-1"/>
      <move select="Counter Rotate Right 2 0" hands="right" beats="4"/>
      <move select="Quarter Right" offsetY="1"/>
    </path>
    <path>
      <move select="Quarter Right" offsetX="-1"/>
      <move select="Counter Rotate Right 4 2" hands="right" beats="4"/>
      <move select="Quarter Right" offsetY="1"/>
    </path>
  </tam>

  <tam title="Single Sidetrack" from="Right-Hand Columns" parts="1.5;4">
    <formation>
      <dancer gender="boy" x="3" y="1" angle="0"/>
      <dancer gender="girl" x="3" y="-1" angle="180"/>
      <dancer gender="girl" x="1" y="-1" angle="180"/>
      <dancer gender="boy" x="1" y="1" angle="0"/>
    </formation>
    <path>
      <move select="Quarter Right" offsetY="1"/>
      <move select="Lead Right" beats="4" scaleX="1.5" scaleY="3"/>
      <move select="Quarter Right"/>
    </path>
    <path>
      <move select="Quarter Left" offsetY="1"/>
      <move select="Lead Right" beats="4" scaleX="1.5" scaleY="3"/>
      <move select="Quarter Right" offsetY="1.2"/>
    </path>
    <path>
      <move select="Quarter Right" offsetY="1"/>
      <move select="Hinge Left" beats="4" scaleX=".5"/>
      <move select="Quarter Left" offsetY=".4"/>
    </path>
    <path>
      <move select="Quarter Left" offsetY="1"/>
      <move select="Hinge Left" beats="4" scaleX=".5"/>
      <move select="Quarter Left" offsetY="-.8"/>
    </path>
  </tam>

  <tam title="Single Sidetrack" from="Column of 8" parts="1.5;4">
    <formation>
      <dancer gender="boy" x="4.2" y="0" angle="0"/>
      <dancer gender="girl" x="3.0" y="0" angle="0"/>
      <dancer gender="boy" x="1.8" y="0" angle="0"/>
      <dancer gender="girl" x="0.6" y="0" angle="0"/>
    </formation>
    <path>
      <move select="Quarter Right"/>
      <move select="Lead Right" beats="4" scaleX="3" scaleY="2.2"/>
      <move select="Quarter Right" offsetX="1"/>
    </path>
    <path>
      <move select="Quarter Left"/>
      <move select="Hinge Left" beats="4" scaleY="0.6" offsetY=".4"/>
      <move select="Quarter Left" offsetX="1"/>
    </path>
    <path>
      <move select="Quarter Right"/>
      <move select="Hinge Left" beats="4" scaleY="0.6" offsetY="-.4"/>
      <move select="Quarter Left" offsetX="-1"/>
    </path>
    <path>
      <move select="Quarter Left"/>
      <move select="Lead Right" beats="4" scaleX="3" scaleY="1.4"/>
      <move select="Quarter Right" offsetX="-1"/>
    </path>
  </tam>

  <tam title="Split Sidetrack" from="Right-Hand Columns" parts="1.5;2">
    <formation>
      <dancer gender="boy" x="3" y="1" angle="0"/>
      <dancer gender="girl" x="3" y="-1" angle="180"/>
      <dancer gender="girl" x="1" y="-1" angle="180"/>
      <dancer gender="boy" x="1" y="1" angle="0"/>
    </formation>
    <path>
      <move select="Quarter Right"/>
      <move select="Counter Rotate Right 2 0"/>
      <move select="Quarter Right" offsetY="1"/>
    </path>
    <path>
      <move select="Quarter Left"/>
      <move select="Counter Rotate Right 0 -2"/>
      <move select="Quarter Right" offsetY="1"/>
    </path>
    <path>
      <move select="Quarter Right"/>
      <move select="Counter Rotate Right 2 0"/>
      <move select="Quarter Right" offsetY="1"/>
    </path>
    <path>
      <move select="Quarter Left"/>
      <move select="Counter Rotate Right 0 -2"/>
      <move select="Quarter Right" offsetY="1"/>
    </path>
  </tam>

  <tam title="Split Sidetrack" from="Right-Hand Waves" parts="1.5;2"
       formation="Ocean Waves RH BGBG">
    <path>
      <move select="Quarter Left" offsetX="1"/>
      <move select="Counter Rotate Right 0 -2"/>
      <move select="Quarter Right"/>
    </path>
    <path>
      <move select="Quarter Right" offsetX="-1"/>
      <move select="Counter Rotate Right 2 0"/>
      <move select="Quarter Right"/>
    </path>
    <path>
      <move select="Quarter Left" offsetX="1"/>
      <move select="Counter Rotate Right 0 -2"/>
      <move select="Quarter Right"/>
    </path>
    <path>
      <move select="Quarter Right" offsetX="-1"/>
      <move select="Counter Rotate Right 2 0"/>
      <move select="Quarter Right"/>
    </path>
  </tam>

</tamination>

=== mpogue2/SquareDesk/SquareDesk-DEV/Taminations/c3b/reactivate.xml
<?xml version="1.0"?>
<!DOCTYPE tamination SYSTEM "tamination.dtd">
<!--

    Copyright 2017 Brad Christie

    This file is part of Taminations.

    Taminations is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published
    by the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    Taminations is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with Taminations.  If not, see <http://www.gnu.org/licenses/>.

-->
<tamination title="Reactivate">

  <tam title="Reactivate" from="Quarter Tag" fractions="3;3">
    <formation>
      <dancer gender="girl" x="3" y="-1" angle="180"/>
      <dancer gender="boy" x="3" y="1" angle="180"/>
      <dancer gender="boy" x="0" y="3" angle="0"/>
      <dancer gender="girl" x="0" y="1" angle="180"/>
    </formation>
    <path>
      <move select="Extend Left" beats="1.5" scaleX="1.5" scaleY=".5"/>
      <move select="Extend Right" beats="1.5" scaleX="1.5" scaleY=".5"/>
      <move select="Swing Right" scaleX=".5"/>
      <move select="Extend Left" beats="3" scaleX="2" scaleY="2"/>
    </path>
    <path>
      <move select="Forward" beats="3"/>
      <move select="Swing Left" scaleX=".5"/>
    </path>
    <path>
      <move select="Lead Right" beats="6" scaleX="4" scaleY="3"/>
      <move select="Lead Right" beats="3" scaleX="3" scaleY="2"/>
    </path>
    <path>
      <move select="Extend Left" beats="2" scaleX="1.5" scaleY=".5"/>
      <move select="Extend Right" beats="1" scaleX=".5" scaleY=".5"/>
      <move select="Swing Left" scaleX=".5"/>
    </path>
  </tam>

  <tam title="Reactivate" from="Left-Hand Quarter Tag"
       formation="Quarter Tag LH" fractions="3;3">
    <path>
      <move select="Forward" beats="3"/>
      <move select="Swing Right" scaleX=".5"/>
    </path>
    <path>
      <move select="Extend Left" beats="1.5" scaleX="1.5" scaleY=".5"/>
      <move select="Extend Right" beats="1.5" scaleX="1.5" scaleY=".5"/>
      <move select="Swing Left" scaleX=".5"/>
      <move select="Extend Right" beats="3" scaleX="2" scaleY="2"/>
    </path>
    <path>
      <move select="Lead Left" beats="6" scaleX="4" scaleY="3"/>
      <move select="Lead Left" beats="3" scaleX="3" scaleY="2"/>
    </path>
    <path>
      <move select="Extend Left" beats="2" scaleX="1.5" scaleY=".5"/>
      <move select="Extend Right" beats="1" scaleX=".5" scaleY=".5"/>
      <move select="Swing Right" scaleX=".5"/>
    </path>
  </tam>

  <tam title="Reactivate" from="Quarter Lines"
       formation="Quarter Lines RH" fractions="3;3">
    <path>
      <move select="Forward" beats="3"/>
      <move select="Swing Right" scaleX=".5"/>
    </path>
    <path>
      <move select="Extend Left" beats="1.5" scaleX="1.5" scaleY=".5"/>
      <move select="Extend Right" beats="1.5" scaleX="1.5" scaleY=".5"/>
      <move select="Swing Left" scaleX=".5"/>
      <move select="Extend Right" beats="3" scaleX="2" scaleY="2"/>
    </path>
    <path>
      <move select="Extend Left" beats="2" scaleX="1.5" scaleY=".5"/>
      <move select="Extend Right" beats="1" scaleX=".5" scaleY=".5"/>
      <move select="Swing Right" scaleX=".5"/>
    </path>
    <path>
      <move select="Lead Right" beats="4" scaleX="4" scaleY="3"/>
      <move select="Lead Right" beats="5" scaleX="5" scaleY="2"/>
    </path>
  </tam>

  <tam title="Reactivate" from="Quarter Waves"
       formation="Quarter Wave RH" fractions="3;3">
    <path>
      <move select="Extend Left" beats="1.5" scaleX="1.5" scaleY=".5"/>
      <move select="Extend Right" beats="1.5" scaleX="1.5" scaleY=".5"/>
      <move select="Swing Right" scaleX=".5"/>
      <move select="Extend Left" beats="3" scaleX="2" scaleY="2"/>
    </path>
    <path>
      <move select="Stand" beats="3"/>
      <move select="Run Right" offsetX="-1"/>
    </path>
    <path>
      <move select="Lead Right" beats="6" scaleX="4" scaleY="3"/>
      <move select="Lead Right" beats="3" scaleX="3" scaleY="2"/>
    </path>
    <path>
      <move select="Extend Left" beats="2" scaleX="1.5" scaleY=".5"/>
      <move select="Extend Right" beats="1" scaleX=".5" scaleY=".5"/>
      <move select="Flip Left" scaleX=".5"/>
    </path>
  </tam>

  <tam title="Cross Reactivate" from="Quarter Tag" formation="Quarter Tag" fractions="">
    <path>
      <move select="Forward" beats="3"/>
      <move select="Swing Right" scaleX=".5"/>
    </path>
    <path>
      <move select="Extend Left" beats="2" scaleX="2" scaleY="2"/>
      <move select="Forward"/>
      <move select="Swing Right" scaleX=".5"/>
      <move select="Extend Left" beats="3" scaleX="2" scaleY="2"/>
    </path>
    <path>
      <move select="Lead Right" beats="6" scaleX="4" scaleY="3"/>
      <move select="Lead Right" beats="3" scaleX="3" scaleY="2"/>
    </path>
    <path>
      <move select="Extend Left" beats="3" scaleX="2" scaleY="2"/>
      <move select="Swing Right" scaleX=".5"/>
    </path>
  </tam>

</tamination>

=== mpogue2/SquareDesk/SquareDesk-DEV/Taminations/c3a/follow_to_a_diamond.xml
<?xml version="1.0"?>
<!DOCTYPE tamination SYSTEM "tamination.dtd">
<!--

    Copyright 2017 Brad Christie

    This file is part of Taminations.

    Taminations is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published
    by the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    Taminations is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with Taminations.  If not, see <http://www.gnu.org/licenses/>.

-->
<tamination title="Follow to a Diamond">

  <tam title="Follow to a Diamond"
       from="Right-Hand Box">
    <formation name="Box RH">
      <dancer gender="boy" y="2" x="1" angle="270"/>
      <dancer gender="girl" y="2" x="-1" angle="90"/>
    </formation>
    <path couples="1 3">
      <move select="Forward 2" beats="1.5" offsetY="-.125" />
      <move select="Swing Right" scaleX=".875" scaleY=".875" />
      <move select="Lead Right" beats="2" offsetX="2" offsetY=".125" />
    </path>
    <path couples="3 1">
      <move select="Run Right" beats="4" />
      <move select="Forward 2" beats="2.5" />
    </path>
  </tam>

  <tam title="Follow to a Diamond"
       from="Left-Hand Box"
       formation="Box LH"
       fractions="" >
    <path>
      <move select="Run Left" beats="4" />
      <move select="Forward 2" beats="2.5" />
    </path>
    <path>
      <move select="Forward 2" beats="1.5" offsetY=".125" />
      <move select="Swing Left" scaleX=".875" scaleY=".875" />
      <move select="Lead Left" beats="2" offsetX="2" offsetY="-.25" />
    </path>
  </tam>

  <tam title="Follow to a Diamond"
       from="Right-Hand Waves"
       formation="Ocean Waves RH BGBG"
       fractions="" >
    <path>
      <move select="Forward 2" beats="1.5" offsetY="-.125" />
      <move select="Swing Right" scaleX=".875" scaleY=".875" />
      <move select="Lead Right" beats="2" offsetX="2" offsetY=".125" />
    </path>
    <path>
      <move select="Run Right" beats="4" />
      <move select="Forward 2" beats="2.5" />
    </path>
    <path>
      <move select="Forward 2" beats="1.5" offsetY="-.125" />
      <move select="Swing Right" scaleX=".875" scaleY=".875" />
      <move select="Lead Right" beats="2" offsetX="2" offsetY=".125" />
    </path>
    <path>
      <move select="Run Right" beats="4" />
      <move select="Forward 2" beats="2.5" />
    </path>
  </tam>

  <tam title="Follow to a Diamond"
       from="Left-Hand Waves"
       formation="Ocean Waves LH BGBG">
    <path>
      <move select="Run Left" beats="4" />
      <move select="Forward 2" beats="2.5" />
    </path>
    <path>
      <move select="Forward 2" beats="1.5" offsetY=".125" />
      <move select="Swing Left" scaleX=".875" scaleY=".875" />
      <move select="Lead Left" beats="2" offsetX="2" offsetY="-.125" />
    </path>
    <path>
      <move select="Run Left" beats="4" />
      <move select="Forward 2" beats="2.5" />
    </path>
    <path>
      <move select="Forward 2" beats="1.5" offsetY=".125" />
      <move select="Swing Left" scaleX=".875" scaleY=".875" />
      <move select="Lead Left" beats="2" offsetX="2" offsetY="-.125" />
    </path>
  </tam>

  <tam title="Follow to a Diamond" from="Right-Hand Columns"
       formation="Column RH GBGB">
    <path>
      <move select="Run Right" beats="5.5" />
      <move select="Forward" />
    </path>
    <path>
      <move select="Forward" beats="1.5" offsetY="-.25" />
      <move select="Swing Right" scaleX=".75" scaleY=".75" />
      <move select="Lead Right" beats="2" offsetX=".5" offsetY=".25" />
    </path>
    <path>
      <move select="Run Right" beats="5.5" scaleX=".5"/>
      <move select="Forward"  />
    </path>
    <path>
      <move select="Forward" beats="1.5" offsetY="-.25" />
      <move select="Swing Right" scaleX=".75" scaleY=".75" />
      <move select="Lead Right" beats="2" offsetX=".5" offsetY=".25" />
    </path>
  </tam>

  <tam title="Follow to a Diamond" from="Left-Hand Columns"
       formation="Column LH GBGB">
    <path>
      <move select="Forward" beats="1.5" offsetY=".25" />
      <move select="Swing Left" scaleX=".75" scaleY=".75" />
      <move select="Lead Left" beats="2" offsetX=".5" offsetY="-.25" />
    </path>
    <path>
      <move select="Run Left" beats="5.5" scaleX=".5"/>
      <move select="Forward"  />
    </path>
    <path>
      <move select="Forward" beats="1.5" offsetY=".25" />
      <move select="Swing Left" scaleX=".75" scaleY=".75" />
      <move select="Lead Left" beats="2" offsetX=".5" offsetY="-.25" />
    </path>
    <path>
      <move select="Run Left" beats="5.5" />
      <move select="Forward" />
    </path>
  </tam>

  <tam title="Follow to a Diamond" from="T-Bones" formation="T-Bone URUR">
    <path>
      <move select="Forward" beats="1.5" offsetY="-.25" />
      <move select="Swing Right" scaleX=".75" scaleY=".75" />
      <move select="Lead Right" beats="2" offsetX="2" offsetY=".25" />
    </path>
    <path>
      <move select="Run Left" beats="5" scaleX=".5"/>
      <move select="Forward"/>
    </path>
    <path>
      <move select="Forward" beats="1.5" offsetY="-.25" />
      <move select="Swing Right" scaleX=".75" scaleY=".75" />
      <move select="Lead Right" beats="2" offsetX="2" offsetY=".25" />
    </path>
    <path>
      <move select="Run Left" beats="5"/>
      <move select="Forward"/>
    </path>
  </tam>

  <tam title="All 8 Follow to a Diamond" formation="Static MiniWaves RH" group=" ">
    <path>
      <move select="Forward 3" beats="2" />
      <move select="Swing Right"  />
      <move select="Lead Right" beats="3" offsetX="2" />
    </path>
    <path>
      <move select="Run Right" beats="5" />
      <move select="Forward 3"/>
    </path>
    <path>
      <move select="Forward 3" beats="2" />
      <move select="Swing Right" />
      <move select="Lead Right" beats="3" offsetX="2" />
    </path>
    <path>
      <move select="Run Right" beats="5" />
      <move select="Forward 3"/>
    </path>
  </tam>

  <tam title="As Couples Follow to a Diamond" formation="Two-Faced Lines RH" group=" ">
    <path>
      <move select="Forward 2" hands="right"/>
      <move select="Run Right" beats="5" hands="right" scaleX="2" scaleY="3"/>
      <move select="Forward" hands="right"/>
      <move select="Lead Right" hands="right" beats="3" scaleX="3" scaleY="3"/>
    </path>
    <path>
      <move select="Forward 2" hands="left"/>
      <move select="Run Right" beats="5" hands="left"/>
      <move select="Forward" hands="left"/>
      <move select="Lead Right" hands="left" beats="3"/>
    </path>
    <path>
      <move select="Run Right" beats="8" hands="left"/>
      <move select="Forward 2" beats="3" hands="left"/>
    </path>
    <path>
      <move select="Run Right" beats="8" hands="right" scaleX="3" scaleY="3"/>
      <move select="Forward 2" beats="3" hands="right"/>
    </path>
  </tam>

  <tam title="Tandem Follow to a Diamond" formation="Column RH GBGB" group=" ">
    <path>
      <move select="Run Right" beats="5"/>
      <move select="Forward 4"/>
    </path>
    <path>
      <move select="Forward 2"/>
      <move select="Run Right" beats="5"/>
      <move select="Forward 2"/>
    </path>
    <path>
      <move select="Forward 2"/>
      <move select="Counter Rotate Right 0 -2" hands="right"/>
      <move select="Counter Rotate Right 0 -2" hands="right"/>
      <move select="Lead Right" beats="3" scaleX="2" scaleY="2"/>
    </path>
    <path>
      <move select="Forward 2"/>
      <move select="Counter Rotate Right 2 0" hands="right"/>
      <move select="Counter Rotate Right 2 0" hands="right"/>
      <move select="Forward 2" beats="1.5"/>
      <move select="Quarter Right" beats="1.5" offsetX="2"/>
    </path>
  </tam>

</tamination>
